[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-uart"
version = "0.1.0"

[workspace]

[dependencies.defmt]
version = "0.2"

[dependencies.defmt-rtt]
version = "0.2"

[dependencies.drogue-device]
path = "../../../device"
features = ["defmt", "defmt-info", "chip+nrf52833"]

# TODO: Get rid of these
[dependencies.embassy]
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "nrf-port-any-edge"
features = ["defmt", "defmt-info" ]

[dependencies.embassy-nrf]
#git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "nrf-port-any-edge"
features = ["defmt", "defmt-info", "52833" ]

[dependencies.cortex-m-rt]
version = "0.6"

[dependencies.cortex-m]
version = "0.7"
features = ["inline-asm"]

[dependencies.panic-probe]
version = "0.2.0"
features = ["print-defmt"]

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
