[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
name = "drogue-lora"
version = "0.1.0"
edition = "2018"
description = "Generic types and APIs for LoRa protocol"