[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
drogue-device-kernel = { path = "../kernel" }
drogue-device-actors = { path = "../actors" }
drogue-device-macros = { path = "../macros" }
drogue-lora = { path = "../traits/lora" }
drogue-sx127x = { path = "../drivers/lora/sx127x", optional = true }

embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false } #, path = "../../../embassy/embassy" }
embassy-nrf = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-nrf" }
embassy-stm32 = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-stm32" }
embassy-rp = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-rp" }
embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-std" }

embedded-hal = { version = "0.2.4", features = ["unproven"], optional = true }

[dev-dependencies]
embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false } #, path = "../../../embassy/embassy-std" }

[features]
std = ["embassy/std", "embassy-std", "embedded-hal"]
"chip+nrf52833" = ["embassy-nrf", "embassy-nrf/52833"]
"chip+stm32l0x2" = ["embassy-stm32", "embassy-stm32/stm32l0x2" ]
"lora+sx127x" = ["drogue-sx127x", "drogue-sx127x/log"]
log = ["embassy/log", "drogue-device-actors/log", "drogue-device-kernel/log" ]
lora = []
defmt = ["embassy/defmt", "drogue-device-actors/defmt", "drogue-device-kernel/defmt" ]
defmt-default = [ ]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
