[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
drogue-device-macros = { path = "../macros" }

embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false } #, path = "../../../embassy/embassy" }
embassy-nrf = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-nrf" }
embassy-stm32 = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-stm32" }
embassy-rp = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-rp" }
embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true } #, path = "../../../embassy/embassy-std" }

# LoRa dependencies
lorawan-device = { git = "https://github.com/lulf/rust-lorawan.git", rev = "45e3d2e07d5d6a2c0abe617db09a2ec946948339", default-features = false, optional = true }
lorawan-encoding = { git = "https://github.com/lulf/rust-lorawan.git", rev = "45e3d2e07d5d6a2c0abe617db09a2ec946948339", default-features = false, features = ["default-crypto"], optional = true }
bit_field = { version = "0.10", optional = true }

# Wifi Dependencies
nom = { version = "6.1.2", default-features = false, optional = true }
moveslice = { version = "2.0", optional = true }

# Utilities
futures = { version = "0.3", default-features = false }
heapless = "0.6"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
atomic-polyfill = "0.1"
generic-array = "0.14"

# Logging alternatives
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

[dev-dependencies]
embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false } #, path = "../../../embassy/embassy-std" }
futures = { version = "0.3", default-features = false, features = ["executor"] }
arrayvec = { version = "0.7" }

[features]
default = [ "log" ]
std = ["embassy/std", "embassy-std"]
"chip+nrf52833" = ["embassy-nrf", "embassy-nrf/52833"]
"chip+stm32l0x2" = ["embassy-stm32", "embassy-stm32/stm32l0x2" ]
"lora+sx127x" = ["lorawan-device", "lorawan-encoding", "bit_field", "log"]
"wifi+esp8266" = ["log", "nom", "moveslice"]
lora = []
wifi = []
fonts = []

defmt-default = [ ]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
