[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies.drogue-device-kernel]
path = "../kernel"
features = ["defmt", "defmt-trace"]

[dependencies.drogue-device-actors]
path = "../actors"
features = ["defmt", "defmt-trace"]

[dependencies.drogue-device-macros]
path = "../macros"

[dependencies.drogue-device-lora]
path = "../traits/lora"
optional = true

[dependencies.drogue-device-sx127x]
path = "../drivers/lora/sx127x"
optional = true


[dependencies.embassy]
#git = "https://github.com/drogue-iot/embassy.git"
#branch = "drogue"
path = "../../../embassy/embassy"
default-features = false

[dependencies.embassy-nrf]
#git = "https://github.com/drogue-iot/embassy.git"
#branch = "drogue"
path = "../../../embassy/embassy-nrf"
default-features = false
optional = true

[dependencies.embassy-std]
#git = "https://github.com/drogue-iot/embassy.git"
#branch = "drogue"
path = "../../../embassy/embassy-std"
default-features = false
optional = true

[dev-dependencies.embassy-std]
#git = "https://github.com/drogue-iot/embassy.git"
#branch = "drogue"
path = "../../../embassy/embassy-std"
default-features = false

[dependencies.log]
version = "0.4"
optional = true

[dependencies.defmt]
version = "0.2"
optional = true

[dependencies.embedded-hal]
version = "0.2.4"
features = ["unproven"]
optional = true

[features]
"chip+nrf52833" = ["embassy-nrf", "embassy-nrf/52833"]
"lora+sx127x" = ["drogue-device-lora", "drogue-device-sx127x"]
std = ["embassy/std", "embassy-std", "embedded-hal"]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
