[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device-example-std-hello"
version = "0.1.0"

[workspace]

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.8"

[dependencies.drogue-device-kernel]
path = "../../../kernel"
features = ["log", "std"]

[dependencies.embassy]
version = "0.1.0"
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "drogue-device"
features = [ "log", "std" ]

[dependencies.embassy-std]
version = "0.1.0"
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "drogue-device"
