[package]
name = "stm32-esp8266"
version = "0.1.0"
authors = ["Jim Crossley <jim@crossleys.org>"]
edition = "2018"
readme = "README.md"

[workspace]

[dependencies]
panic-probe = { version = "0.2.0", features = ["print-rtt"] }
rtt-logger = "0.1"
rtt-target = {version = "0.2", features = ["cortex-m"] }
log = "0.4"
heapless = "0.7"
cortex-m = "0.7"
cortex-m-rt = "0.6"

drogue-device = { path = "../../../device", features = ["wifi+esp8266", "chip+stm32f401"], default-features = false }

# TODO: Get rid of these
# embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false } #, path = "../../../embassy/embassy" }
# embassy-stm32 = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false} #, path = "../../../embassy/embassy-stm32" }
